/**
 * Eleventy configuration.
 *
 * Input is src/; output is dist/ (the only deployed directory).
 * All data lives in src/_data/*.json, generated by scripts/build/*.
 */
export default function (eleventyConfig) {
  eleventyConfig.addPassthroughCopy({
    'src/assets': 'assets',
    'src/styles': 'styles',
    'src/scripts': 'scripts',
    'src/admin': 'admin',
  });

  // ---------- filters ----------

  /** Look up a mission record by id. */
  eleventyConfig.addFilter('missionById', (missions, id) =>
    missions.find(m => m.id === id)
  );

  /** Mutating push for building arrays inside njk loops. */
  eleventyConfig.addFilter('push', (arr, item) => {
    arr.push(item);
    return arr;
  });

  /**
   * Build a compact SVG relationship graph: the mission at center with its
   * related missions arranged radially. `related` items carry
   * { id, type, name }. Returns raw SVG markup.
   */
  eleventyConfig.addFilter('relGraph', (mission, related) => {
    const W = 640;
    const H = 300;
    const cx = W / 2;
    const cy = H / 2;
    if (!related || related.length === 0) return '';

    const esc = s =>
      String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    const shortName = name => {
      const clean = String(name).replace(/\s*\(.*?\)\s*/g, ' ').trim();
      return clean.length > 14 ? clean.slice(0, 13) + '…' : clean;
    };

    const nodes = related.map((rel, i) => {
      const angle = -Math.PI / 2 + (i * 2 * Math.PI) / related.length;
      return {
        x: cx + Math.cos(angle) * cx * 0.72,
        y: cy + Math.sin(angle) * cy * 0.62,
        ...rel,
      };
    });

    const links = nodes
      .map(n => `<line class="link" x1="${cx}" y1="${cy}" x2="${n.x}" y2="${n.y}"/>`)
      .join('');
    const dots = nodes
      .map(
        n => `<a href="/missions/${n.id}/" class="node">
          <title>${esc(n.name)} — ${esc(n.type)}</title>
          <circle cx="${n.x}" cy="${n.y}" r="7"/>
          <text x="${n.x}" y="${n.y - 12}">${esc(shortName(n.name))}</text>
        </a>`
      )
      .join('');

    return `<svg class="rel-graph" viewBox="0 0 ${W} ${H}" role="img"
      aria-label="Relationship graph: ${esc(mission.name)} connected to ${related.length} related missions">
      ${links}
      <g class="node self">
        <circle cx="${cx}" cy="${cy}" r="10"/>
        <text x="${cx}" y="${cy - 16}">${esc(shortName(mission.name))}</text>
      </g>
      ${dots}
    </svg>`;
  });

  /** Human date from ISO string: "1957-10-04" -> "4 Oct 1957". */
  eleventyConfig.addFilter('humanDate', iso => {
    if (!iso) return null;
    const [y, mo, d] = iso.split('-').map(Number);
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
      'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return `${d} ${months[mo - 1]} ${y}`;
  });

  /** Thousands-separated number: 83600 -> "83,600". */
  eleventyConfig.addFilter('numberFormat', n =>
    Number(n).toLocaleString('en-US')
  );

  /** Wordmark initials for agency marks: "United States civil space
      program" -> "US", "Scaled Composites" -> "SC". */
  eleventyConfig.addFilter('initials', name => {
    const words = String(name)
      .replace(/[^A-Za-z0-9 ]/g, ' ')
      .split(/\s+/)
      .filter(w => w && !['the', 'of', 'and', 'for'].includes(w.toLowerCase()));
    return words.slice(0, 3).map(w => w[0].toUpperCase()).join('');
  });

  /** Find a country record by id. */
  eleventyConfig.addFilter('findCountry', (countries, id) =>
    countries.find(c => c.id === id)
  );

  /** Missions launched on today's month/day (uses launch_date when known). */
  eleventyConfig.addFilter('onThisDay', missions => {
    const now = new Date();
    const mmdd = `${String(now.getMonth() + 1).padStart(2, '0')}-${String(
      now.getDate()
    ).padStart(2, '0')}`;
    return missions.filter(
      m => m.launch_date && m.launch_date.slice(5) === mmdd
    );
  });

  /** Era accent CSS variable by era prefix. */
  eleventyConfig.addFilter('eraAccent', era => {
    const prefixes = ['1957–1969:', '1970–1985:', '1986–2000:',
      '2001–2012:', '2013–2020:', '2021–Present:'];
    const idx = prefixes.findIndex(p => String(era).startsWith(p));
    return `var(--era-${idx + 1}, var(--color-accent))`;
  });

  /** Era index (1-6) for accent lookups in templates. */
  eleventyConfig.addFilter('eraIndex', era => {
    const prefixes = ['1957–1969:', '1970–1985:', '1986–2000:',
      '2001–2012:', '2013–2020:', '2021–Present:'];
    return prefixes.findIndex(p => String(era).startsWith(p)) + 1;
  });

  /** Missions sorted chronologically (year ascending, stable). */
  eleventyConfig.addFilter('sortByYear', missions =>
    [...missions].sort((a, b) => a.year - b.year)
  );

  return {
    dir: {
      input: 'src',
      output: 'dist',
      includes: '_includes',
      data: '_data',
    },
    templateFormats: ['njk', 'md'],
    htmlTemplateEngine: 'njk',
  };
}
